
version: '2.4'

services:

  # debug env:
  # tty:
  #   image: postgres:13.1
  #   init: true
  #   command: tail -f /dev/null

  db:
    image: postgres:13.1
    environment:
      - POSTGRES_PASSWORD=${ALYX_DB_PASSWORD?set ALYX_DB_PASSWORD in .env}
    healthcheck:
      test: [ "CMD", "/usr/bin/psql", "-U", "postgres", "-c", "\\l" ]
      timeout: 5s
      retries: 60
      interval: 1s

  alyx:
    image: alyx-docker
    build:
      context: .
    init: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PGUSER=${ALYX_DB_USER?set ALYX_DB_USER in .env}
      - PGHOST=${ALYX_DB_HOST?set ALYX_DB_HOST in .env}
      - PGPASSWORD=${ALYX_DB_PASSWORD?set ALYX_DB_PASSWORD in .env}
    ports:
      - '8000:8000'
    volumes:
      - ./dump.sql.gz:/dump.sql.gz
      # - ./alyx:/alyx

